#!/usr/bin/env python3

import cgi
import cgitb
import sqlite3

import process_form
from reg_request_db import RegDb

debugdir = '/tmp'
datadir  = '/var/spool/registration'
dbfile   = '{}/account_queue.db'.format(datadir)

cgitb.enable(display=0, logdir=debugdir)
the_form = cgi.FieldStorage()

print('Content-type: text/html\n')

try:
    reg_db = RegDb(dbfile)

except ConnectionError as ce:
    print('''{start}

<h1>Internal Error</h1>

<p>The registration system is currently unavailable.  Please try back later.</p>

<p>Exception:</br>
{the_error}
</p>

{end}'''.format(start     = process_form.header,
                end       = process_form.footer,
                the_error = ce)
    )

else:
    print(process_form.header)

    print(process_form.start_form)
    
    for candidate in reg_db.candidates():
        print(process_form.candidate_template.format(*candidate.string_values('print'), reqid=candidate.reqid()))

    print(process_form.end_form)

    print(process_form.footer)
