#!/usr/bin/env python3

import cgi
import cgitb
import html
import re
import sqlite3

import member
import process_form
from reg_request_db import RegDb

debugdir = '/tmp'
datadir  = '/var/spool/registration'
dbfile   = '{}/account_queue.db'.format(datadir)

cgitb.enable(display=0, logdir=debugdir)
the_form = cgi.FieldStorage()

print('Content-type: text/html\n')

try:
    reg_db = RegDb(dbfile)

except ConnectionError as ce:
    print('''{start}

<h1>Internal Error</h1>

<p>The registration system is currently unavailable.  Please try back later.</p>

<p>Exception:</br>
{the_error}
</p>

{end}'''.format(start     = process_form.header,
                end       = process_form.footer,
                the_error = ce)
    )

else:
    if "act" not in the_form:

        print(process_form.header)
        print(process_form.start_form)
        
        for candidate in reg_db.candidates():
            print(process_form.candidate_template.format(
                *candidate.string_values('print'),
                reqid=candidate.reqid())
                )

        print(process_form.end_form)
        print(process_form.footer)

    else:
        deletions = (var for var in the_form if 'del_' in var)
        canceled  = {}
        for deletion in deletions:
            reqid = (deletion.split('_'))[-1]
            canceled[reqid] = True
            try:
                reg_db.delete(reqid)
            except RuntimeError as rte:
                print("<strong>No can delete: {} (id: {})</strong></br>".format(rte, reqid))
            else:
                print("<strong>Request id {} is gawn.</strong></br>".format(reqid))

        modifications = (var for var in the_form if 'mod_' in var)
        for mod in modifications:
            reqid = (mod.split('_'))[-1]
            if not re.search(r'\D', reqid) and reqid not in canceled:
                fields = member.ordered_field_names()
                for field in fields:
                    val = the_form[field+'_'+reqid].value
                    try:
                        reg_db.modify(reqid, field, val)
                    except RuntimeError as rte:
                        print("<strong>No can modify: {} (id: {})</strong></br>".format(rte, reqid))
                    else:
                        print("<strong>Modified id {}, field {}. Now: {}</strong></br>".format(
                            reqid, field, val))
            else:
                print("<strong>Cannot modify request id {}: malformed or deleted.</strong></br>".format(reqid))

        # registrations = ...
