#!/usr/bin/env python3

import cgi
import cgitb
import sqlite3

import member import Member
import reg_form
from reg_request_db import RegDb

debugdir = '/tmp'
datadir  = '/var/spool/registration'
dbfile   = '{}/account_queue.db'.format(datadir)

reg_db = RegDb(dbfile)

cgitb.enable(display=0, logdir=debugdir)
the_form = cgi.FieldStorage()


print('Content-type: text/html\n')

if "email" not in the_form:
    reg_form.print_form()

else:
    print(reg_form.header)

    the_member = Member(*list(the_form[var].value for var in 
                    ("first", "last", "email", "addr1",
                        "city", "state", "zipcode", "username")))
    if "addr2" in the_form:
        the_member.addr2 = the_form["addr2"].value

    reg_db.insert(the_member)

    reg_db.print_queue()

    print(reg_form.footer)
