#!/usr/bin/env python3

import cgi
import cgitb
import html
import sqlite3
import sys

from member import Member
import reg_form
from reg_request_db import RegDb

debugdir = '/tmp'
datadir  = '/var/spool/registration'
dbfile   = '{}/account_queue.db'.format(datadir)

cgitb.enable(display=0, logdir=debugdir)
the_form = cgi.FieldStorage()

print('Content-type: text/html\n')

if "email" not in the_form:
    print(reg_form.full_form)

else:
    try:
        reg_db = RegDb(dbfile)

    except:
        print('''{start}

<h1>Internal Error</h1>

The registration system is currently unavailable.  Please try back later.

{end}'''.format(start=reg_form.header, end=reg_form.footer))

        sys.exit(1)

    else:
        the_member = Member(*list(html.escape(the_form[var].value) for var in 
                        ("first", "last", "email", "addr1",
                            "city", "state", "zipcode", "username")))

        if "addr2" in the_form:
            the_member.set_addr2(the_form["addr2"].value)

        print(reg_form.header)

        try:
            reg_db.insert(the_member)

        except RuntimeError as e:
            print("<p><strong>Error: {}</strong></p>".format(str(e)))

        reg_db.print_queue()

        print('''
<p>Thank you for requesting membership in TriLUG!  Be sure to come to a meeting in
person in order to complete the process.  See you there!</p>

{end}'''.format(end = reg_form.footer))
