#!/usr/bin/env python3

import cgi
import cgitb
import sqlite3
import sys

import member import Member
import reg_form
from reg_request_db import RegDb

debugdir = '/tmp'
datadir  = '/var/spool/registration'
dbfile   = '{}/account_queue.db'.format(datadir)

cgitb.enable(display=0, logdir=debugdir)
the_form = cgi.FieldStorage()

print('Content-type: text/html\n')

if "email" not in the_form:
    reg_form.print_form()

else:
    try:
        reg_db = RegDb(dbfile)

    except:
        print('''{start}

<h1>Internal Error</h1>

The registration system is currently unavailable.  Please try back later.

{end}'''.format(start=reg_form.header, end=reg_form.footer))

        sys.exit(1)

    else:
        the_member = Member(*list(the_form[var].value for var in 
                        ("first", "last", "email", "addr1",
                            "city", "state", "zipcode", "username")))

        if "addr2" in the_form:
            the_member.addr2 = the_form["addr2"].value

        print(reg_form.header)

        try:
            reg_db.insert(the_member)

        except Error as e:
            print("<strong>Error: {}</strong></br>".format(str(e)))

        reg_db.print_queue()
        print(reg_form.footer)
