#!/usr/bin/env python3

import cgi
import cgitb
import html

import reg_form
import reg_scrub
import register

from member import Member
from reg_request_db import RegDb

debugdir = '/tmp'
cgitb.enable(display=0, logdir=debugdir)

the_form = cgi.FieldStorage()

print('Content-type: text/html\n')

if "email" not in the_form:
    print(reg_form.full_form)

else:
    try:
        reg_db = RegDb(register.database)

    except:
        print('''{start}

<h1>Internal Error</h1>

The registration system is currently unavailable.  Please try back later.

{end}'''.format(start=reg_form.header, end=reg_form.footer))

    else:
        print(reg_form.header)
        try:
            the_member = Member(*list(html.escape(the_form[var].value) for var in 
                            Member.ordered_field_names()
                            if var in the_form
                            and reg_scrub.val_ok(the_form[var].value)))

        except TypeError:
            print('<p><strong>Error:  Required field(s) not filled out.</strong></p>')

        else:
            try:
                reg_db.insert(the_member)

            except RuntimeError as e:
                print('<p><strong>Error: {err}</strong></p>'.format(err = str(e)))

            else:
                print('''
<p>Thank you for requesting membership in TriLUG!  Be sure to come to a meeting in
person in order to complete the process.  See you there!</p>
''')

        print(reg_form.footer)
